name: pyguibank
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyqt
  - loguru
  - openpyxl
  - pandas
  - pip
  - matplotlib
  - scikit-learn
  - seaborn
  - sqlalchemy
  - jsonschema
  - nltk
  - pyinstaller=5.13
  - nsis
  - requests>=2.32,<3
  - pip:
      - pdfplumber==0.11.4
